name: Node.js CI

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (scripts/dep)
        working-directory: scripts/dep
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Upload ZIP Release
        uses: actions/upload-artifact@v4
        with:
          name: "ZIP Release"
          path: dist/com.kureichi.discordrpc.zip

      - name: Upload ZXP Release
        uses: actions/upload-artifact@v4
        with:
          name: "ZXP Release"
          path: dist/com.kureichi.discordrpc.zxp
